// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

package mocks

import (
	"context"
	"reflect"

	"go.uber.org/mock/gomock"
)

type MockGreeter struct {
	ctrl     *gomock.Controller
	recorder *MockGreeterMockRecorder
}

type MockGreeterMockRecorder struct {
	mock *MockGreeter
}

func NewMockGreeter(ctrl *gomock.Controller) *MockGreeter {
	mock := &MockGreeter{ctrl: ctrl}
	mock.recorder = &MockGreeterMockRecorder{mock: mock}
	return mock
}

func (mock *MockGreeter) EXPECT() *MockGreeterMockRecorder {
	return mock.recorder
}

func (mock *MockGreeter) Greet(ctx context.Context, name string) (string, error) {
	mock.ctrl.T.Helper()
	results := mock.ctrl.Call(mock, "Greet", ctx, name)
	greeting, _ := results[0].(string)
	err, _ := results[1].(error)
	return greeting, err
}

func (recorder *MockGreeterMockRecorder) Greet(ctx, name any) *gomock.Call {
	recorder.mock.ctrl.T.Helper()
	return recorder.mock.ctrl.RecordCallWithMethodType(
		recorder.mock,
		"Greet",
		reflect.TypeOf((*MockGreeter)(nil).Greet),
		ctx,
		name,
	)
}
